# [START cloudbuild_builddeploy]
steps:
  - id: 'Build Develop Container Image'
    name: 'gcr.io/cloud-builders/docker:$_DOCKER_VERSION'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}', '.']

  - id: 'Push Develop Container Image'
    name: 'gcr.io/cloud-builders/docker:$_DOCKER_VERSION'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}']

  - id: 'Deploy to Develop Cloud Run Job'
    name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run jobs deploy ${_SERVICE} \
          --image gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA} \
          --region ${_SERVICE_REGION} \
          --max-retries 3 \
          --tasks 1 \
          --task-timeout 600s

options:
  env:
    - 'CLOUDSDK_RUN_REGION=${_SERVICE_REGION}'
    - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: devops-cus-service1
  _SAMPLE_DIR: devops-cus-service1
  _SERVICE_REGION: asia-south1
  _CLOUDSDK_VERSION: latest
  _DOCKER_VERSION: latest
# [END cloudbuild_builddeploy]
